#!/bin/zsh

# wttr.in
export WEATHER_TEMPERATURE_UNIT=c
export WEATHER_TIME_FORMAT=24h
export WEATHER_WINDSPEED_UNIT="km/h"
export WEATHER_SHOW_ICON=True
export WEATHER_SHOW_LOCATION=True
export WEATHER_SHOW_TODAY_DETAILS=True
export WEATHER_FORECAST_DAYS=7
export WEATHER_LOCATION="Iowa City"
